# Generated by Django 5.2.3 on 2026-01-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_downloadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='lat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='lng',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='category',
            field=models.CharField(choices=[('Branch', 'Branch'), ('Extension', 'Extension'), ('Booth', 'Booth')], max_length=15),
        ),
    ]
