# Generated by Django 5.2.3 on 2026-02-26 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_branch_lat_branch_lng_alter_branch_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Daily News Flash', 'Daily News Flash'), ('Daily Market Update', 'Daily Market Update'), ('Weekly Market Review', 'Weekly Market Review'), ('Weekly Mutual Fund Report', 'Weekly Mutual Fund Report'), ('Equity Snapshot', 'Equity Snapshot'), ('IPO Insights', 'IPO Insights'), ('Earning Updates', 'Earning Updates'), ('Macro Report', 'Macro Report'), ('Sector Report', 'Sector Report')], max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='research/')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='marketnews',
            options={'ordering': ['-publish_date'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
