# Generated by Django 5.2.7 on 2026-06-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_research_alter_marketnews_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='category',
            field=models.CharField(choices=[('DailyNewsFlash', 'Daily News Flash'), ('DailyMarketUpdate', 'Daily Market Update'), ('WeeklyMarketReview', 'Weekly Market Review'), ('WeeklyMutualFundReport', 'Weekly Mutual Fund Report'), ('EquitySnapshot', 'Equity Snapshot'), ('IPOInsights', 'IPO Insights'), ('EarningUpdates', 'Earning Updates'), ('MacroReport', 'Macro Report'), ('SectorReport', 'Sector Report')], max_length=50),
        ),
    ]
